export const ContainsLiquid = {
  data: [
    {
      id: 1,
      weight: "TR 0.0 kq-dan 0.10 kq-a qədər",
      price: 1.5,
      isLiquid: false,
      countryId: 1,
    },
    {
      id: 2,
      weight: "TR 0.1 kq-dan 0.25 kq-a qədər",
      price: 2.5,
      isLiquid: false,
      countryId: 1,
    },
    {
      id: 3,
      weight: "TR 0.75 kq-dan 1.0 kq-a qədər",
      price: 8.0,
      isLiquid: true,
      countryId: 1,
    },
    {
      id: 4,
      weight: "ABS 0.0 kq-dan 0.25 kq-a qədər",
      price: 2.5,
      isLiquid: false,
      countryId: 2,
    },
    {
      id: 5,
      weight: "ABS 0.25 kq-dan 0.5 kq-a qədər",
      price: 4.0,
      isLiquid: false,
      countryId: 2,
    },
    {
      id: 6,
      weight: "ABS 0.5 kq-dan 0.75 kq-a qədər",
      price: 5.5,
      isLiquid: false,
      countryId: 2,
    },
    {
      id: 7,
      weight: "CIN 0.25 kq-dan 0.5 kq-a qədər",
      price: 6.9,
      isLiquid: false,
      countryId: 3,
    },
    {
      id: 8,
      weight: "ALM 0.01 kq-dan 0.25 kq-a qədər",
      price: 3.8,
      isLiquid: false,
      countryId: 4,
    },
  ],
};
